/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/computer_terminal.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Comp_Screen000_TerminalMaterial_0: THREE.Mesh
    Comp_Screen002_TerminalMaterial_0: THREE.Mesh
  }
  materials: {
    TerminalMaterial: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/computer_terminal.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Comp_Screen000_TerminalMaterial_0.geometry} material={materials.TerminalMaterial} position={[18.161, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={212.25} />
          <mesh geometry={nodes.Comp_Screen002_TerminalMaterial_0.geometry} material={materials.TerminalMaterial} position={[18.161, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={212.25} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/computer_terminal.glb')
